services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: always
