name: Build and Deploy Production

on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: node1
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build Container
        run: |
          docker compose build

      - name: Deploy to server
        run: |
          docker compose up -d
